apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sandbox
  labels:
    app: techtrends
    tag: latest
  name: techtrends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
      tag: latest
  template:
    metadata:
      labels:
        app: techtrends
        tag: latest
    spec:
      containers:
        - image: shershebnev/techtrends:latest
          imagePullPolicy: IfNotPresent
          name: techtrends
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          ports:
            - containerPort: 3111
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 3111
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 3111
